DATASET_ABS: 'dmwater_dataset'
TRAIN_DIR: 'FEM_large_ke_kd/train'
VAL_DIR: 'FEM_large_ke_kd/valid'
ROLLOUT_STEPS: 800
N_HIS: 6
PRED_STEPS: 1
MAX_VAL: 30
KINEMATIC_PARTICLE_ID: 0
NUM_PARTICLE_TYPES: 2
SOLVER:
  BASE_LR: 1.0e-4
  MIN_LR: 1.0e-6
  WEIGHT_DECAY: 0.0
  MAX_ITERS: 5e6
  WARMUP_ITERS: 0
  VAL_INTERVAL: 25000
  BATCH_SIZE: 1
  LR_DECAY_INTERVAL: 5e6
NET:
  PARTICLE_EMB_SIZE: 16
  MAX_EDGE_PER_PARTICLE: 200 # previously 150
  SELF_EDGE: True
  NODE_FEAT_DIM_IN: 31 # 15 + 6 + 16 (6 is the dist_to_wall) (previously 30 = 10 + 4 + 16)
  EDGE_FEAT_DIM_IN: 4 # 1 + 3 (previously 3=1+2)
  GNN_LAYER: 10
  HIDDEN_SIZE: 128
  OUT_SIZE: 3 # 2 (previously 2)
  NOISE: 0.00067
  RADIUS: 1.5 # 0.3 previously